<Switch>:
    active_norm_pos: max(0., min(1., (int(self.active) + self.touch_distance / sp(app.get_scaled_width(41)))))
    canvas:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            source: 'atlas://data/images/defaulttheme/switch-background{}'.format('_disabled' if self.disabled else '')
            size: sp(app.get_scaled_width(83)), sp(app.get_scaled_height(32))
            pos: int(self.center_x - sp(app.get_scaled_width(41))), int(self.center_y - sp(app.get_scaled_height(16)))
    canvas.after:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            source: 'atlas://data/images/defaulttheme/switch-button{}'.format('_disabled' if self.disabled else '')
            size: sp(app.get_scaled_width(43)), sp(app.get_scaled_height(32))
            pos: int(self.center_x - sp(app.get_scaled_width(41)) + self.active_norm_pos * sp(app.get_scaled_width(41))), int(self.center_y - sp(app.get_scaled_height(16)))

[FileIconEntry@Widget]:
    locked: False
    path: ctx.path
    selected: self.path in ctx.controller().selection
    size_hint: None, None

    on_touch_down: self.collide_point(*args[1].pos) and ctx.controller().entry_touched(self, args[1])
    on_touch_up: self.collide_point(*args[1].pos) and ctx.controller().entry_released(self, args[1])
    size: dp(app.get_scaled_width(100)), dp(app.get_scaled_height(100))

    canvas:
        Color:
            rgba: 1, 1, 1, 1 if self.selected else 0
        BorderImage:
            border: 8, 8, 8, 8
            pos: root.pos
            size: root.size
            source: 'atlas://data/images/defaulttheme/filechooser_selected'

    Image:
        size: dp(app.get_scaled_width(48)), dp(app.get_scaled_height(48))
        source: 'filechooser_%s' % ('folder' if ctx.isdir else 'file') + '.png'
        pos: root.x + dp(app.get_scaled_width(24)), root.y + dp(app.get_scaled_height(40))
    Label:
        text: ctx.name
        text_size: (root.width, self.height)
        halign: 'center'
        shorten: True
        size: dp(app.get_scaled_width(100)), dp(app.get_scaled_height(16))
        pos: root.x, root.y + dp(app.get_scaled_height(16))
        font_size: str(app.get_scaled_width(15)) + "sp"

    Label:
        text: '{}'.format(ctx.get_nice_size())
        color: .8, .8, .8, 1
        size: dp(app.get_scaled_width(100)), dp(app.get_scaled_height(16))
        pos: root.pos
        halign: 'center'
        font_size: str(app.get_scaled_width(11)) + "sp"


[FileListEntry@FloatLayout+TreeViewNode]:
    locked: False
    entries: []
    path: ctx.path
    # FIXME: is_selected is actually a read_only treeview property. In this
    # case, however, we're doing this because treeview only has single-selection
    # hardcoded in it. The fix to this would be to update treeview to allow
    # multiple selection.
    is_selected: self.path in ctx.controller().selection

    orientation: 'horizontal'
    size_hint_y: None
    height: dp(app.get_scaled_height(48)) if dp(1) > 1 else dp(app.get_scaled_height(24))
    # Don't allow expansion of the ../ node
    is_leaf: not ctx.isdir or ctx.name.endswith('..' + ctx.sep) or self.locked
    on_touch_down: self.collide_point(*args[1].pos) and ctx.controller().entry_touched(self, args[1])
    on_touch_up: self.collide_point(*args[1].pos) and ctx.controller().entry_released(self, args[1])
    BoxLayout:
        pos: root.pos
        size_hint_x: None
        width: root.width - dp(app.get_scaled_width(10))
        Label:
            id: filename
            text_size: self.width, None
            halign: 'left'
            shorten: True
            text: ctx.name
            font_size: str(app.get_scaled_width(15)) + "sp"
        Label:
            text_size: self.width, None
            size_hint_x: None
            halign: 'right'
            text: '{}'.format(ctx.get_nice_size())
            font_size: str(app.get_scaled_width(15)) + "sp"